In [1]:
import numpy as np

In [9]:
#1 Shape and size
cars = np.array([[1,2,3],
                 [10,101,100],
                 [10,101,100]])
#print(type(cars))
#print(cars.shape)
print(cars.size)

9


In [38]:
#Basic Arithmetic 

a = np.array([10,50,2])
b = np.array([20,30,40])

print('this is an addition',a + b)
print('this is subtraction', a - b)
print('this is an addition',a * b)
print('this is subtraction', a / b)


(3,)
this is an addition [30 80 42]
this is subtraction [-10  20 -38]
this is an addition [ 200 1500   80]
this is subtraction [0.5        1.66666667 0.05      ]


In [25]:
#indexing and slicing
M = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,13],
              [12,13,14,15]])

print(M[3,0])

print(M[3])

print(M[1:3,1:3])

12
[12 13 14 15]
[[ 6  7]
 [10 11]]


In [36]:
#Reshaping Arrays
'''
flat = np.array([[12,23,3,4],
              [5,6,7,83],
              [9,10,113,13],
              [12,13,14,15]])
'''
flat = np.arange(18)
#print(flat)
grid2 = flat.reshape(3,6)
grid2


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [44]:
#brodCasting
X = np.array([[1,2,1],
              [0,2,3]])
Y = np.array([2,3,4])

print(X + Y)

[[3 5 5]
 [2 5 7]]


In [48]:
#Usefull Built-in Fuctions 
the_mean = np.mean(X)
print('this is the mean for X:',the_mean)

sum_up = np.sum(X)
print('this is the sum',sum_up)

min_up = np.min(X)
print('this is the minimum value',min_up)


this is the mean for X: 1.5
this is the sum 9
this is the minimum value 0


In [50]:
#Advanced Linear Algebra(Not done)

A = np.array([[12,12],
             [12,34]])
B = np.array([[1,4,5],
              [10,20,40]])

print(A.dot(B))

[[ 132  288  540]
 [ 352  728 1420]]


In [53]:
#Advanced: Random Numbers(Not done)
#r = np.random.rand(10)
#print(r)

M = np.random.randn(3,3)
print(M)

[[ 0.09860961 -0.09164831 -0.62800383]
 [-0.95157652  0.04583009  0.81909472]
 [ 0.29725303 -0.79244121  0.08961692]]


In [104]:
#simple project:Rolling Dice Sim
dice1 = np.random.randint(1,7,size=1000)
dice2 = np.random.randint(1,7,size=1000)

sums = dice1 + dice2

count7 = np.sum(sums == 7)

print(count7)
prob7 = count7/1000
print(f"Probability of rolling a 7: {prob7:.1f}")




612
Probability of rolling a 7: 0.6


In [ ]:
#Next Steps
#Practice slicing and broadcasting with small arrays.

#Explore np.where, np.unique, and boolean masking.

#Build a simple linear regression from scratch using NumPy’s linear algebra.

#When you’re comfortable, move on to pandas for tabular data.